const el=(tag,attrs={},children=[])=>{const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>{if(k==='class')n.className=v;else if(k==='style')Object.assign(n.style,v);else if(k.startsWith('on')&&typeof v==='function')n.addEventListener(k.slice(2),v);else n.setAttribute(k,v)});children.forEach(c=>{if(c==null)return;if(typeof c==='string')n.appendChild(document.createTextNode(c));else n.appendChild(c)});return n}
const mount=(root,children=[])=>{root.innerHTML='';children.forEach(c=>root.appendChild(c))}
const storeKey='alfawiseGameProgress'
const loadStore=()=>{try{return JSON.parse(localStorage.getItem(storeKey)||'{}')}catch(e){return{}}}
const saveStore=(s)=>localStorage.setItem(storeKey,JSON.stringify(s))
const initStore=()=>{const s=loadStore();if(!s.version)s.version='2.0.0';if(!s.unlockedTitles)s.unlockedTitles=[];if(!s.difficulty)s.difficulty='简单';if(!s.progress)s.progress={};saveStore(s);return s}
const difficulties=['简单','挑战','专业']
const levels=[{id:'clean',name:'淨化森林（清）'},{id:'balance',name:'平衡花園（調）'},{id:'energy',name:'能量泉源（補）'},{id:'shape',name:'塑型神殿（朔）'},{id:'meal',name:'餐量管理大師'}]
const shuffle=(arr)=>{const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));const t=a[i];a[i]=a[j];a[j]=t}return a}
const normalizeQuestion=(item)=>{if(item.choices&&Array.isArray(item.choices)){const c=item.choices.filter(x=>!!x.correct).length;if(c!==1)throw new Error('每題僅允許一個正確答案');if(item.choices.length!==4)throw new Error('每題必須四個選項');return{ text:item.q||item.text, choices:item.choices, explain:item.explain||'' }}const opts=item.options||[];const correctIdx=item.answer;const base=[];if(opts.length===2){base.push({text:opts[0],correct:correctIdx===0});base.push({text:opts[1],correct:correctIdx===1});base.push({text:'與題幹無關的說法',correct:false});base.push({text:'以上皆非',correct:false})}else{for(let i=0;i<4;i++){const t=opts[i]||`選項${String.fromCharCode(65+i)}`;base.push({text:t,correct:i===correctIdx})}}const ccount=base.filter(c=>c.correct).length;if(ccount!==1)throw new Error('每題僅允許一個正確答案');return{ text:item.q, choices:base, explain:item.explain||'' }}
const buildRunFromRaw=(rawItems)=>{const qs=(rawItems||[]).map(normalizeQuestion);const order=shuffle([...qs.keys()]);const n=qs.length;const base=Math.floor(n/4);const counts=[base,base,base,base];let rem=n-base*4;const addOrder=[1,2,3,0];for(let i=0;i<rem;i++){counts[addOrder[i%4]]++}const posPool=[];for(let p=0;p<4;p++){for(let k=0;k<counts[p];k++)posPool.push(p)}const posShuffled=shuffle(posPool);const runChoices=order.map((qi,idx)=>{const q=qs[qi];const correct=q.choices.find(c=>c.correct);const wrongs=shuffle(q.choices.filter(c=>!c.correct));const target=posShuffled[idx];const arr=new Array(4);arr[target]=correct;let wi=0;for(let p=0;p<4;p++){if(arr[p])continue;arr[p]=wrongs[wi++]}return{ qIndex:qi, choices:arr, text:q.text, explain:q.explain }});return{ order, runChoices }}
const levelQuestionsCache={}
const fetchLevelQuestions=async(levelId)=>{if(levelQuestionsCache[levelId])return levelQuestionsCache[levelId];try{const res=await fetch(`./data/${levelId}.json`,{cache:'no-store'});if(!res.ok)throw new Error('題庫載入失敗：'+res.status);const json=await res.json();levelQuestionsCache[levelId]=json;return json}catch(err){return null}}
const loadQuestions=async(diff,levelId)=>{const all=await fetchLevelQuestions(levelId);if(!all){return [{q:'示例題目：本關題庫載入失敗時的備援題',options:['是','否'],answer:0,explain:'請確認以HTTP方式開啟並檔案存在'}]}const arr=all[diff];if(!arr||!arr.length){return [{q:'示例題目：此難度題庫為空',options:['是','否'],answer:0,explain:'請在對應JSON補齊題目'}]}return arr}
let appRoot=document.getElementById('app')
let state={store:initStore(),view:'home',levelId:null,qIndex:0,countdown:10,timer:null,answered:false,correctCount:0,run:null,lastError:null}
const toast=(msg)=>{const t=el('div',{class:'toast'},[msg]);document.body.appendChild(t);setTimeout(()=>{t.remove()},1800)}
const header=()=>{const s=state.store;const chips=s.unlockedTitles.map(t=>el('span',{class:'badge'},[t]));return el('div',{class:'site-header'},[el('div',{class:'brand'},[el('div',{class:'logo'}),el('h1',{},['清調補朔·趣味闖關學習'])]),el('div',{class:'header-actions'},[el('span',{class:'badge'},[`模式：${s.difficulty}`]),...chips])])}
const homeView=()=>{const s=state.store;const diffRow=el('div',{class:'difficulty'},difficulties.map(d=>el('span',{class:`badge-diff ${s.difficulty===d?'active':''}`,onClick:()=>{s.difficulty=d;saveStore(s);mountApp()}},[d])));const start=el('button',{class:'btn btn-primary',onClick:()=>{state.view='levels';mountApp()}},['開始闖關']);const resume=el('button',{class:'btn btn-ghost',onClick:()=>{const last=s.progress.last;if(last&&last.view){state.view=last.view;state.levelId=last.levelId;state.qIndex=last.qIndex||0;mountApp()}else toast('暫無可恢復進度')}},['恢復進度']);return el('div',{class:'main'},[header(),el('div',{class:'panel'},[el('h2',{class:'title'},['主線故事']),el('p',{class:'subtitle'},['扮演騎士，回答產品知識拯救亞健康公主']),diffRow,el('div',{},[start,' ',resume])])])}
const levelsView=()=>{const s=state.store;const grid=el('div',{class:'grid'},levels.map(l=>el('div',{class:'level-card'},[el('div',{class:'level-body'},[el('div',{class:'level-title'},[l.name]),el('div',{class:'level-meta'},[el('span',{},[(s.progress&&s.progress[s.difficulty]&&s.progress[s.difficulty][l.id]&&s.progress[s.difficulty][l.id].passed)?'已通關':'未完成']),el('button',{class:'btn btn-secondary',onClick:()=>{state.levelId=l.id;state.view='loading';mountApp();loadQuestions(s.difficulty,l.id).then(raw=>{state.run=buildRunFromRaw(raw);state.qIndex=0;state.correctCount=0;state.view='quiz';mountApp()}).catch(e=>{state.lastError=(e&&e.message)||'關卡載入失敗';state.view='error';mountApp()})}},['進入關卡'])])])])));const back=el('button',{class:'btn btn-ghost',onClick:()=>{state.view='home';mountApp()}},['返回首頁']);return el('div',{class:'main'},[header(),el('div',{class:'panel'},[el('h2',{class:'title'},['選擇關卡']),grid,el('div',{},[back])])])}
const persistProgress=()=>{const s=state.store;if(!s.progress[s.difficulty])s.progress[s.difficulty]={};if(!s.progress[s.difficulty][state.levelId])s.progress[s.difficulty][state.levelId]={};s.progress.last={view:state.view,levelId:state.levelId,qIndex:state.qIndex};saveStore(s)}
const ensureTimerStopped=()=>{if(state.timer){clearInterval(state.timer);state.timer=null}}
const startCountdown=()=>{ensureTimerStopped();state.countdown=10;const bar=document.querySelector('.progress .bar');const st=performance.now();state.timer=setInterval(()=>{const t=Math.max(0,10-(performance.now()-st)/1000);state.countdown=Math.ceil(t);const w=Math.max(0,t/10*100);if(bar)bar.style.width=w+'%';if(t<=0){ensureTimerStopped();state.view='timeout';persistProgress();mountApp()}},100)}
const quizView=()=>{const s=state.store;const data=(state.run&&state.run.runChoices);if(!data||!data.length){state.lastError='題庫缺失或載入失敗';return errorView('題庫缺失')}const item=data[state.qIndex];const title=el('h2',{class:'title'},[levels.find(x=>x.id===state.levelId).name]);const q=el('div',{class:'question'},[item.text]);const progress=el('div',{class:'progress'},[el('div',{class:'bar'})]);const footer=el('div',{class:'quiz-footer'},[el('span',{},[`題目 ${state.qIndex+1}/${data.length}`]),el('span',{},[`剩餘 ${state.countdown}s`])]);const explain=el('div',{class:'explain',style:{display:'none'}},[item.explain]);const labels=['A','B','C','D'];const opts=el('div',{class:'options'},item.choices.map((opt,idx)=>{const o=el('div',{class:'option',onClick:()=>{if(state.answered)return;state.answered=true;ensureTimerStopped();if(!!opt.correct){o.classList.add('correct');state.correctCount++;explain.style.display=''}else{o.classList.add('wrong');toast('答錯了，重新挑戰')}persistProgress();setTimeout(()=>{state.answered=false;if(!opt.correct){state.view='loading';mountApp();loadQuestions(s.difficulty,state.levelId).then(raw=>{state.run=buildRunFromRaw(raw);state.qIndex=0;state.correctCount=0;state.view='quiz';mountApp()}).catch(e=>{state.lastError=(e&&e.message)||'重新載入失敗';state.view='error';mountApp()})}else{state.qIndex++;if(state.qIndex>=data.length){const pass=state.correctCount===data.length;if(!s.progress[s.difficulty])s.progress[s.difficulty]={};s.progress[s.difficulty][state.levelId]={passed:pass,score:state.correctCount,total:data.length};saveStore(s);state.view='level-complete';mountApp()}else mountApp()}},600)}},[`${labels[idx]}. ${opt.text}`]);return o}));const actions=el('div',{},[el('button',{class:'btn btn-ghost',onClick:()=>{ensureTimerStopped();state.view='levels';mountApp()}},['退出關卡'])]);const panel=el('div',{class:'panel quiz'},[title,progress,q,opts,explain,footer,actions]);const layout=el('div',{class:'main'},[header(),panel]);setTimeout(()=>{startCountdown()},0);persistProgress();return layout}
const loadingView=()=>{return el('div',{class:'main'},[header(),el('div',{class:'panel'},[el('h2',{class:'title'},['關卡載入中']),el('p',{class:'subtitle'},['正在準備題目與資源，請稍候…']),el('div',{class:'progress'},[el('div',{class:'bar'})])])])}
const timeoutView=()=>{const msg=el('p',{class:'subtitle'},['超時未答，已跳轉提示頁面']);const back=el('button',{class:'btn btn-primary',onClick:()=>{state.view='quiz';mountApp()}},['返回題目']);return el('div',{class:'main'},[header(),el('div',{class:'panel'},[el('h2',{class:'title'},['時間到']),msg,el('div',{},[back])])])}
const levelCompleteView=()=>{const s=state.store;const lvl=s.progress[s.difficulty][state.levelId];const meta=levels.find(x=>x.id===state.levelId);const title=el('h2',{class:'title'},[meta.name]);const info=el('p',{class:'subtitle'},[`得分 ${lvl.score}/${lvl.total}，${lvl.passed?'通關成功':'通關失敗'}`]);const back=el('button',{class:'btn btn-primary',onClick:()=>{state.view='levels';state.levelId=null;mountApp()}},['返回關卡']);const home=el('button',{class:'btn btn-ghost',onClick:()=>{state.view='home';state.levelId=null;mountApp()}},['返回首頁']);return el('div',{class:'main'},[header(),el('div',{class:'panel'},[title,info,el('div',{},[back,' ',home])])])}
const errorView=(msg)=>el('div',{class:'main'},[header(),el('div',{class:'panel'},[el('h2',{class:'title'},['錯誤']),el('p',{class:'subtitle'},[msg]),state.lastError?el('div',{class:'explain'},[String(state.lastError)]):null])])
const mountApp=()=>{let v;if(state.view==='home')v=homeView();else if(state.view==='levels')v=levelsView();else if(state.view==='quiz')v=quizView();else if(state.view==='loading')v=loadingView();else if(state.view==='timeout')v=timeoutView();else if(state.view==='level-complete')v=levelCompleteView();else v=homeView();mount(appRoot,[v])}
window.addEventListener('error',(e)=>{state.lastError=(e&&(e.message||e.error&&e.error.message))||'未知錯誤'})
mountApp()
